<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-08-08 05:54
=======
# Generated by Django 3.0.8 on 2020-08-08 08:38
>>>>>>> dc19faeac713516434d0d50b3b7889b37409b25d
=======
# Generated by Django 3.0.8 on 2020-08-09 10:51
>>>>>>> 32d83660b0617f2d526fb38bbb38b067e7549e2d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, default="I'm using SoCL Media!", max_length=280)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
